micronaut:
  application:
    name: numbers-api
  server:
    cors:
      enabled: true

temporal:
  frontend: localhost:7233
  namespace: default

grpc:
  channels:
    cache-service:
      address: localhost:8081
      plaintext: true
      max-retry-attempts: 10


